version: '3.8'
services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb:latest
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - '8081:8081'

  app:
    build:
      context: .
      dockerfile: Dockerfile
      restart: on-failure
      target: development
    command: pnpm start:dev
    ports:
      - '3000:3000'
    depends_on:
      - database
    volumes:
      - ./:/app/src
      - /app/node_modules
